# Generated by Django 4.2.7 on 2024-03-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=100)),
                ('stuemail', models.EmailField(max_length=150)),
                ('stuage', models.IntegerField()),
                ('stuphoto', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('stubranch', models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('electronic', 'Electronic Engineering')], max_length=100)),
                ('stucontact', models.CharField(max_length=20)),
            ],
        ),
    ]
